version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "weekly"
    groups:
      npm-major:
        update-types:
          - "major"
      npm-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "weekly"
    groups:
      composer-major:
        update-types:
          - "major"
      composer-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/resources/docker/dockerfiles"
    target-branch: "2.x"
    ignore:
      - dependency-name: "node"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - '*'

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - '*'
